/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xrtziukbvnsmbhonckvt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhydHppdWtidm5zbWJob25ja3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MjY0MzUsImV4cCI6MjA4NDUwMjQzNX0.3PYVb5yt8Sqfn4UkCsDd-44cAn9ySWPRKjnX-DLGTEA"